name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      VERNAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v3


    - name: Setup 
      run: |
        sudo apt-get update && sudo apt-get install -y make ca-certificates
        sudo update-ca-certificates

    - name: Build
      run: |
        make lin_bin VERSION="${{ env.VERNAME }}"

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: linbin
        path: autoortho_lin_*.bin


  build-windows:
    runs-on: windows-latest

    env:
      VERNAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v3
   
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Setup 
      run: |
          #choco --yes install winfsp
          python -m pip install -U pytest 
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r requirements-build.txt

    - name: Build
      run: |
        make win_exe VERSION="${{ env.VERNAME }}"
        make win_zip ZIP="7z a" VERSION="${{ env.VERNAME }}"

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: winbin
        path: |
          AutoOrtho_*.exe
          autoortho_win_*.zip
