name: Nightly Release 

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  getcalver:
    runs-on: ubuntu-latest
    outputs:
      calver: ${{ steps.getcalver.outputs.CALVER }}
    steps:
      - name: Get CalVer
        id: getcalver
        run: |
          echo "CALVER="$(date +%Y.%m.%d) > $GITHUB_OUTPUT

  build:
    needs: getcalver 
    uses: ./.github/workflows/build_release.yml
    with:
      version: ${{ needs.getcalver.outputs.calver }}
      relname: nightly 
